{-# LANGUAGE OverloadedStrings #-}

-- | Test file I/O by generating code for test struct
module Main (main) where

import Data.Text (Text)
import qualified Data.Text as T
import qualified Data.Text.IO as TIO
import System.FilePath ((</>))

import Structify.IR.Types
import Structify.CodeGen

-- | Create a simple test struct (same as in test/Spec.hs)
testStruct :: EnrichedStruct
testStruct = EnrichedStruct
  { esName = StructName "Person"
  , esFields =
      [ EnrichedField
          { efName = FieldName "name"
          , efType = PointerType (PrimitiveType "char") Owned
          , efAnnotations = defaultFieldAnnotations
              { faDefault = Just "NULL"
              }
          , efBitField = Nothing
          , efLocation = Nothing
          }
      , EnrichedField
          { efName = FieldName "age"
          , efType = PrimitiveType "int"
          , efAnnotations = defaultFieldAnnotations
              { faDefault = Just "0"
              }
          , efBitField = Nothing
          , efLocation = Nothing
          }
      , EnrichedField
          { efName = FieldName "children"
          , efType = PointerType (PointerType (StructType (StructName "Person")) Owned) Owned
          , efAnnotations = defaultFieldAnnotations
              { faLengthField = Just (FieldName "num_children")
              , faDeepCopy = True
              }
          , efBitField = Nothing
          , efLocation = Nothing
          }
      , EnrichedField
          { efName = FieldName "num_children"
          , efType = PrimitiveType "size_t"
          , efAnnotations = defaultFieldAnnotations
              { faDefault = Just "0"
              }
          , efBitField = Nothing
          , efLocation = Nothing
          }
      ]
  , esAnnotations = defaultStructAnnotations
  , esLocation = Nothing
  }

main :: IO ()
main = do
  putStrLn "=== Testing File I/O ==="
  putStrLn ""

  -- Generate all functions
  let generated = generateAllFunctions testStruct

  -- Write header file
  let headerFile = "examples/simple/person_generated.h"
  putStrLn $ "Writing header to: " ++ headerFile
  TIO.writeFile headerFile $ generateHeaderFile "person.h" (gcHeaderDeclarations generated)

  -- Write source file
  let sourceFile = "examples/simple/person_generated.c"
  putStrLn $ "Writing source to: " ++ sourceFile
  TIO.writeFile sourceFile $ generateSourceFile "person_generated.h" (gcSourceDefinitions generated)

  putStrLn ""
  putStrLn "✓ Files generated successfully!"
  putStrLn $ "  Header: " ++ headerFile
  putStrLn $ "  Source: " ++ sourceFile

-- | Generate header file content with includes
generateHeaderFile :: FilePath -> Text -> Text
generateHeaderFile inputFile content = T.unlines
  [ "// Generated by structify from: " <> T.pack inputFile
  , ""
  , "#ifndef PERSON_GENERATED_H"
  , "#define PERSON_GENERATED_H"
  , ""
  , "#include <stdbool.h>"
  , "#include <stdint.h>"
  , "#include <stddef.h>"
  , "#include <stdio.h>"
  , "#include <errno.h>"
  , ""
  , "// Include original header"
  , "#include \"" <> T.pack inputFile <> "\""
  , ""
  , "// Generated function declarations"
  , content
  , ""
  , "#endif // PERSON_GENERATED_H"
  ]

-- | Generate source file content with includes
generateSourceFile :: FilePath -> Text -> Text
generateSourceFile headerFile content = T.unlines
  [ "// Generated by structify"
  , ""
  , "#include \"" <> T.pack headerFile <> "\""
  , "#include <string.h>"
  , "#include <stdlib.h>"
  , ""
  , "// Generated function definitions"
  , content
  ]
