// Generated by structify

#include "person_generated.h"
#include <string.h>
#include <stdlib.h>

// Generated function definitions
// Init function
int person_init(Person* self) {
    if (self == NULL) {
        errno = EINVAL;
        return -1;
    }
    // Initialize fields
    self->name = NULL;
    self->age = 0;
    self->children = NULL;
    self->num_children = 0;

    return 0;
}

// Cleanup function
void person_cleanup(Person* self) {
    if (self == NULL) {
        return;
    }
    // Cleanup fields

    self->children = NULL;

    self->name = NULL;

}

// Copy function
int person_copy(Person* dest, const Person* src) {
    if (dest == NULL || src == NULL) {
        errno = EINVAL;
        return -1;
    }
    // Copy fields
    dest->name = src->name;
    dest->age = src->age;
    dest->children = src->children;
    dest->num_children = src->num_children;

    return 0;
cleanup:
    person_cleanup(dest);
    return -1;
}

// Print function
void person_print(const Person* self, FILE* out, int depth) {
    if (self == NULL) {
        fprintf(out, "NULL");
        return;
    }
    if (depth > 10) {
        fprintf(out, "...");
        return;
    }
    fprintf(out, "Person {");
    fprintf(out, "\n  ");
    fprintf(out, "name: ");
    if (self->name != NULL) {
        fprintf(out, "\"%s\"", self->name);
    } else {
        fprintf(out, "NULL");
    }

    fprintf(out, "\n  ");
    fprintf(out, "age: ");
    fprintf(out, "%d", self->age);

    fprintf(out, "\n  ");
    fprintf(out, "children: ");
    if (self->children != NULL) {
        fprintf(out, "%p", (void*)self->children);
    } else {
        fprintf(out, "NULL");
    }

    fprintf(out, "\n  ");
    fprintf(out, "num_children: ");
    fprintf(out, "%d", self->num_children);


    fprintf(out, "}");
}

// Equality functions
bool person_equal(const Person* a, const Person* b) {
    // Handle NULL pointers
    if (a == b) return true;  // Same pointer or both NULL
    if (a == NULL || b == NULL) return false;  // One is NULL
    // Compare fields (primitives first for early exit)
    if (a->age != b->age) return false;

    if (a->num_children != b->num_children) return false;

    if (a->name != b->name) return false;

    if (a->children != b->children) return false;


    return true;
}

bool person_deep_equal(const Person* a, const Person* b) {
    // Handle NULL pointers
    if (a == b) return true;  // Same pointer or both NULL
    if (a == NULL || b == NULL) return false;  // One is NULL
    // Compare fields (primitives first for early exit)
    if (a->age != b->age) return false;

    if (a->num_children != b->num_children) return false;

    if (a->name != b->name) {
        if (a->name == NULL || b->name == NULL) return false;
        if (strcmp(a->name, b->name) != 0) return false;
    }

    if (a->children != b->children) {
        if (a->children == NULL || b->children == NULL) return false;
        if (!person_deep_equal(*a->children, *b->children)) return false;
    }


    return true;
}

// Hash function
uint64_t person_hash(const Person* self) {
    if (self == NULL) return 0;
    // FNV-1a hash (64-bit)
    uint64_t hash = 14695981039346656037ULL;  // FNV offset basis
    const uint64_t fnv_prime = 1099511628211ULL;
    // Hash fields
    if (self->name != NULL) {
        const char* str = self->name;
        while (*str) {
            hash ^= (uint64_t)*str++;
            hash *= fnv_prime;
        }
    }

    {
        const uint8_t* bytes = (const uint8_t*)&self->age;
        for (size_t i = 0; i < sizeof(self->age); i++) {
            hash ^= bytes[i];
            hash *= fnv_prime;
        }
    }

    if (self->children != NULL) {
        const uint8_t* bytes = (const uint8_t*)self->children;
        for (size_t i = 0; i < sizeof(*self->children); i++) {
            hash ^= bytes[i];
            hash *= fnv_prime;
        }
    }

    {
        const uint8_t* bytes = (const uint8_t*)&self->num_children;
        for (size_t i = 0; i < sizeof(self->num_children); i++) {
            hash ^= bytes[i];
            hash *= fnv_prime;
        }
    }


    return hash;
}



