// Generated by structify from: examples/simple/point.h

#ifndef POINT_GENERATED_H
#define POINT_GENERATED_H

#include <stdbool.h>
#include <stdint.h>
#include <stddef.h>
#include <stdio.h>
#include <errno.h>

// Include original header
#include "examples/simple/point.h"

// Generated function declarations
// Init function
int point_init(Point* self);
// Cleanup function
void point_cleanup(Point* self);
// Copy function
int point_copy(Point* dest, const Point* src);
// Print function
void point_print(const Point* self, FILE* out, int depth);
// Equality functions
bool point_equal(const Point* a, const Point* b);
bool point_deep_equal(const Point* a, const Point* b);
// Hash function
uint64_t point_hash(const Point* self);



#endif // POINT_GENERATED_H
