{-# LANGUAGE OverloadedStrings #-}

-- | CLI command implementations
module Structify.CLI.Commands
  ( runCommand
  , runGenerate
  , runValidate
  , runInfo
  ) where

import Data.Text (Text)
import qualified Data.Text as T
import qualified Data.Text.IO as TIO
import Data.Char (toUpper)
import System.FilePath (takeBaseName, replaceExtension)
import System.Exit (exitFailure, exitSuccess)
import Control.Monad (when)

import Structify.CLI.Options
import Structify.CLI.Output
import Structify.IR.Types
import Structify.CodeGen
import Structify (enrichHeader)

-- | Run a command
runCommand :: Bool -> Command -> IO ()
runCommand verbose cmd = case cmd of
  Generate opts -> runGenerate verbose opts
  Validate path -> runValidate verbose path
  Info path -> runInfo verbose path

-- | Run the generate command
runGenerate :: Bool -> GenerateOptions -> IO ()
runGenerate verbose opts = do
  let inputFile = genInputFile opts
      outputHeader = genOutputHeader opts
      outputSource = genOutputSource opts

  when verbose $ putStrLn $ "Reading input file: " ++ inputFile

  -- Parse and enrich the header
  result <- enrichHeader inputFile

  case result of
    Left err -> do
      printError $ "Failed to parse header: " ++ err
      exitFailure

    Right structs -> do
      when verbose $ putStrLn $ "Found " ++ show (length structs) ++ " struct(s)"

      -- Generate code for all structs
      let allGenerated = map generateAllFunctions structs

      -- Combine all declarations and definitions
      let headerContent = T.unlines $ map gcHeaderDeclarations allGenerated
          sourceContent = T.unlines $ map gcSourceDefinitions allGenerated

      -- Determine output file names
      let baseName = takeBaseName inputFile
          headerFile = maybe (baseName ++ "_generated.h") id outputHeader
          sourceFile = maybe (baseName ++ "_generated.c") id outputSource

      -- Write output files
      when verbose $ putStrLn $ "Writing header to: " ++ headerFile
      TIO.writeFile headerFile $ generateHeaderFile inputFile headerContent

      when verbose $ putStrLn $ "Writing source to: " ++ sourceFile
      TIO.writeFile sourceFile $ generateSourceFile headerFile sourceContent

      printSuccess $ "Generated code successfully!"
      printSuccess $ "  Header: " ++ headerFile
      printSuccess $ "  Source: " ++ sourceFile

-- | Run the validate command
runValidate :: Bool -> FilePath -> IO ()
runValidate verbose path = do
  when verbose $ putStrLn $ "Validating: " ++ path

  result <- enrichHeader path

  case result of
    Left err -> do
      printError $ "Validation failed: " ++ err
      exitFailure

    Right structs -> do
      printSuccess $ "Validation passed!"
      printSuccess $ "Found " ++ show (length structs) ++ " valid struct(s)"

      -- Show struct names
      mapM_ (\s -> let StructName name = esName s
                   in putStrLn $ "  - " ++ T.unpack name) structs

-- | Run the info command
runInfo :: Bool -> FilePath -> IO ()
runInfo verbose path = do
  when verbose $ putStrLn $ "Analyzing: " ++ path

  result <- enrichHeader path

  case result of
    Left err -> do
      printError $ "Failed to analyze: " ++ err
      exitFailure

    Right structs -> do
      putStrLn $ "Found " ++ show (length structs) ++ " struct(s):\n"

      mapM_ printStructInfo structs

-- | Print information about a struct
printStructInfo :: EnrichedStruct -> IO ()
printStructInfo struct = do
  let StructName name = esName struct
      fields = esFields struct
      annots = esAnnotations struct

  putStrLn $ "Struct: " ++ T.unpack name
  putStrLn $ "  Fields: " ++ show (length fields)

  mapM_ printFieldInfo fields

  putStrLn ""

-- | Print information about a field
printFieldInfo :: EnrichedField -> IO ()
printFieldInfo field = do
  let FieldName name = efName field
      fieldType = efType field

  putStrLn $ "    " ++ T.unpack name ++ " :: " ++ showType fieldType

-- | Show a type as a string
showType :: EnrichedType -> String
showType (PrimitiveType t) = T.unpack t
showType (PointerType inner ownership) = showType inner ++ "*" ++ " (" ++ show ownership ++ ")"
showType (ArrayType inner size) = showType inner ++ "[" ++ maybe "?" show size ++ "]"
showType (StructType (StructName n)) = "struct " ++ T.unpack n
showType (TypedefType (TypeName n)) = T.unpack n
showType FunctionPointerType = "function pointer"
showType (UnknownType t) = T.unpack t ++ " (unknown)"

-- | Generate header file content with includes
generateHeaderFile :: FilePath -> Text -> Text
generateHeaderFile inputFile content =
  let guardName = makeHeaderGuard inputFile
  in T.unlines
    [ "// Generated by structify from: " <> T.pack inputFile
    , ""
    , "#ifndef " <> guardName
    , "#define " <> guardName
    , ""
    , "#include <stdbool.h>"
    , "#include <stdint.h>"
    , "#include <stddef.h>"
    , "#include <stdio.h>"
    , "#include <errno.h>"
    , ""
    , "// Include original header"
    , "#include \"" <> T.pack inputFile <> "\""
    , ""
    , "// Generated function declarations"
    , content
    , ""
    , "#endif // " <> guardName
    ]

-- | Generate a unique header guard name from a file path
-- Example: "foo/bar.h" -> "FOO_BAR_H_GENERATED"
makeHeaderGuard :: FilePath -> Text
makeHeaderGuard path =
  let baseName = takeBaseName path
      -- Convert to uppercase and replace non-alphanumeric with underscore
      sanitized = T.map sanitizeChar (T.pack baseName)
      sanitizeChar c
        | c >= 'a' && c <= 'z' = toUpper c
        | c >= 'A' && c <= 'Z' = c
        | c >= '0' && c <= '9' = c
        | otherwise = '_'
  in T.toUpper sanitized <> "_GENERATED_H"

-- | Generate source file content with includes
generateSourceFile :: FilePath -> Text -> Text
generateSourceFile headerFile content = T.unlines
  [ "// Generated by structify"
  , ""
  , "#include \"" <> T.pack headerFile <> "\""
  , "#include <string.h>"
  , "#include <stdlib.h>"
  , ""
  , "// Generated function definitions"
  , content
  ]
