// Generated by structify from: person.h

#ifndef PERSON_GENERATED_H
#define PERSON_GENERATED_H

#include <stdbool.h>
#include <stdint.h>
#include <stddef.h>
#include <stdio.h>
#include <errno.h>

// Include original header
#include "person.h"

// Generated function declarations
// Init function
int person_init(Person* self);
// Cleanup function
void person_cleanup(Person* self);
// Copy function
int person_copy(Person* dest, const Person* src);
// Print function
void person_print(const Person* self, FILE* out, int depth);
// Equality functions
bool person_equal(const Person* a, const Person* b);
bool person_deep_equal(const Person* a, const Person* b);
// Hash function
uint64_t person_hash(const Person* self);


#endif // PERSON_GENERATED_H
