// Generated by structify

#include "point_generated.h"
#include <string.h>
#include <stdlib.h>

// Generated function definitions
// Init function
int point_init(Point* self) {
    if (self == NULL) {
        errno = EINVAL;
        return -1;
    }
    // Initialize fields
    self->x = 0;
    self->y = 0;

    return 0;
}

// Cleanup function
void point_cleanup(Point* self) {
    if (self == NULL) {
        return;
    }
    // Cleanup fields



}

// Copy function
int point_copy(Point* dest, const Point* src) {
    if (dest == NULL || src == NULL) {
        errno = EINVAL;
        return -1;
    }
    // Copy fields
    dest->x = src->x;
    dest->y = src->y;

    return 0;
cleanup:
    point_cleanup(dest);
    return -1;
}

// Print function
void point_print(const Point* self, FILE* out, int depth) {
    if (self == NULL) {
        fprintf(out, "NULL");
        return;
    }
    if (depth > 10) {
        fprintf(out, "...");
        return;
    }
    fprintf(out, "Point {");
    fprintf(out, "\n  ");
    fprintf(out, "x: ");
    fprintf(out, "%d", self->x);

    fprintf(out, "\n  ");
    fprintf(out, "y: ");
    fprintf(out, "%d", self->y);


    fprintf(out, "}");
}

// Equality functions
bool point_equal(const Point* a, const Point* b) {
    // Handle NULL pointers
    if (a == b) return true;  // Same pointer or both NULL
    if (a == NULL || b == NULL) return false;  // One is NULL
    // Compare fields (primitives first for early exit)
    if (a->x != b->x) return false;

    if (a->y != b->y) return false;


    return true;
}

bool point_deep_equal(const Point* a, const Point* b) {
    // Handle NULL pointers
    if (a == b) return true;  // Same pointer or both NULL
    if (a == NULL || b == NULL) return false;  // One is NULL
    // Compare fields (primitives first for early exit)
    if (a->x != b->x) return false;

    if (a->y != b->y) return false;


    return true;
}

// Hash function
uint64_t point_hash(const Point* self) {
    if (self == NULL) return 0;
    // FNV-1a hash (64-bit)
    uint64_t hash = 14695981039346656037ULL;  // FNV offset basis
    const uint64_t fnv_prime = 1099511628211ULL;
    // Hash fields
    {
        const uint8_t* bytes = (const uint8_t*)&self->x;
        for (size_t i = 0; i < sizeof(self->x); i++) {
            hash ^= bytes[i];
            hash *= fnv_prime;
        }
    }

    {
        const uint8_t* bytes = (const uint8_t*)&self->y;
        for (size_t i = 0; i < sizeof(self->y); i++) {
            hash ^= bytes[i];
            hash *= fnv_prime;
        }
    }


    return hash;
}



